### ISSUE TITLE
Missing LS372 ops

### ISSUE THREAD

**Issue by mhasself** [simonsobs/ocs-web#35]
Definitely engage_channel, maybe others.

**Comment by sanahabhimani** [comment]
`input_configfile` would be super helpful, is that feasible? 

others to add: `engage_autorange`, `get_input_setup`

I don't feel very strongly about `set_calibration_curve` because that's a likely one-off event that happens in the beginning (and `input_configfile` addresses calibration curve setup as well) but telescope folks may disagree

**Comment by BrianJKoopman** [comment]
A recent request from site - enable entering parameters for [custom_pid](https://socs.readthedocs.io/en/main/agents/lakeshore372.html#socs.agents.lakeshore372.agent.LS372_Agent.custom_pid) in order to servo the focal plane from ocs-web.

**Comment by mhasself** [comment]
For custom_pid, docstring says:
```
P (int) – Proportional value in Watts/Kelvin
I (int) – Integral Value in Hz
update_time (int) – Time between PID updates in seconds
```
However, it will actually accept float for `I`.  But I think all three of these could / should be floats, in the agent.

I'll get the panel ready but consider whether you want to adjust how args are handled.

**Comment by BrianJKoopman** [comment]
Great point. This updates to allow floats everywhere: https://github.com/simonsobs/socs/pull/548

**Comment by mhasself** [comment]
How should custom_pid be situated with respect to the other operations on the panel?  After "set_pid"?

**Comment by BrianJKoopman** [comment]
Hmm, good question. I don't really have a strong opinion on where. Those PID commands are two different PIDs though, so I'm not sure if users will find that confusing (or perhaps already do...)

**Comment by mhasself** [comment]
I believe all the requested ops are now implemented.
