### ISSUE TITLE
Need Restart task for hwp-encoder and hwp-gripper

### ISSUE THREAD

**Issue by ykyohei** [simonsobs/ocs-web#68]
We have recently added a "restart" task to the hwp-encoder and hwp-gripper agents, this task will restart the process running in the beagle bone (https://github.com/simonsobs/socs/pull/738, https://github.com/simonsobs/socs/pull/737).
It is really helpful to have buttons for this task in OCS-web.

**Comment by mhasself** [comment]
Those agents don't have panels, and those new tasks don't take any params.  So it is likely that auto-population is all you need, and that should occur correctly as soon as the new versions of the agents are running.  So I don't think any ocs-web code changes are needed.
